runtime: php83

handlers:
###################################################

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /css
  static_dir: public/css

- url: /img
  static_dir: public/img

####################################################

- url: /og/img/.*
  script: public/ogimg.php

- url: /.*
  script: public/index.php

###################################################

# error_handlers:
# - file: error/default.html

# - error_code: over_quota
#   file: error/over_quota.html

# - error_code: dos_api_denial
#   file: error/over_quota.html
